name: Release Action

on:
  push:
    tags:
      - 'v*'

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
         channel: 'beta'
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter config --enable-linux-desktop
     - run: flutter build linux
     - uses: ncipollo/release-action@v1
       with:
        artifacts: "build/linux/x64/release/bundle"
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: "release_log.md"
